name: Build APK GOR ONDIN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Extract APK project
        run: |
          mkdir build-src
          unzip -q GOR_Ondin_Badminton_APK_ICON_PREMIUM.zip -d build-src

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Build APK
        working-directory: build-src
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GOR-ONDIN-BADMINTON-APK
          path: build-src/app/build/outputs/apk/debug/*.apk
